version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: ["/usr/src/entrypoint.sh"]
    volumes:
      - "./server:/usr/src"
    ports:
      - 5000:5000
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
    depends_on:
      - api-db
  
  api-db:
    build:
      context: ./server/app/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
